name: Send Daily Cat Images

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 12AM UTC (7AM GMT+7)
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Email with Cat Image
        env:
          EMAILJS_USER_ID: "FKkNNZcm0oVGEhYyb"
          EMAILJS_SERVICE_ID: "service_uvala3e"
          EMAILJS_TEMPLATE_ID: "template_u2vu7lr"
        run: |
          curl -X POST "https://api.emailjs.com/api/v1.0/email/send" \
          -H "Content-Type: application/json" \
          -d '{
                "service_id": "service_uvala3e",
                "template_id": "template_u2vu7lr",
                "user_id": "FKkNNZcm0oVGEhYyb"
              }'