name: Send Cat Image Email

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day 
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Contacts
      id: fetch_contacts
      env:
        EMAILJS_USER_ID: "FKkNNZcm0oVGEhYyb"
      run: |
        contacts=$(curl -X GET "https://api.emailjs.com/api/v1.0/contacts" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ env.EMAILJS_USER_ID }}")
        echo "::set-output name=contacts::$contacts"

    - name: Send Email to Contacts
      env:
        EMAILJS_USER_ID: "FKkNNZcm0oVGEhYyb"
        EMAILJS_SERVICE_ID: "service_uvala3e"
        EMAILJS_TEMPLATE_ID: "template_u2vu7lr"
      run: |